In [1]:
import numpy as np
import time

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1, l2)]
end = time.time()
print(add[0:10])

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.17941689491271973


In [2]:
# Using Numpy Arrays

import numpy as np
import time

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.023291826248168945


In [3]:
# Python Zip Explained.

l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1, l2))

[(1, 6), (2, 7), (4, 8)]

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(2, 3)

In [8]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("Numpy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
Numpy array size: 8000 bytes


In [9]:
l1 = [1, 2, 3, 4]

In [10]:
list_squares = [x**2 for x in l1]

In [11]:
list_squares

[1, 4, 9, 16]

In [13]:
numpy_squares = arr**2

In [14]:
numpy_squares

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
import numpy as np
import time

list_data = list(range(1000))
numpy_data = np.array(list_data)

start = time.time()
numpy_squares = arr**2
end = time.time()
print(add[0:10])

[ 0  2  4  6  8 10 12 14 16 18]
