In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,4])

In [3]:
arr

array([1, 3, 4])

In [9]:
np.zeros((3,4)) # Zero matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3, 5))  # Ones Matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full((3, 4), 8)  # Full matrix

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [12]:
np.eye(5)  # Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(1, 100, 20)  # Like Range

array([ 1, 21, 41, 61, 81])

In [15]:
np.linspace(1, 100, 5) 

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [16]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])