In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3]

np.int64(4)

In [7]:
flat[3: 6]

array([4, 5, 6])

In [8]:
flat[: 5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [18]:
flat[3:] # same as flat[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [20]:
b = flat[3: 7]

In [21]:
b

array([4, 5, 6, 7])

In [22]:
b[0] = 44444

In [23]:
b

array([44444,     5,     6,     7])

In [24]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

In [31]:
b = flat[3: 7].copy() # This is not a slice because we are using copy method.

In [32]:
b

array([44444,     5,     6,     7])

In [33]:
b[0] = 44444466

In [34]:
b

array([44444466,        5,        6,        7])

In [35]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

#### 6. Fancy Indexing & Boolean Masking

In [38]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [43]:
arr[[1, 4, 6]]  # Indices to select

array([54,  2, 34])

In [44]:
arr[arr>23]  # Condition : values greater than 25.

array([54, 53, 34])

## Practice
- Exercises for Practice
- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.

In [153]:
arr1 = [1, 2, 30]

In [154]:
arr2 = [4, 55, 6]

In [155]:
arr3 = [71, 8, 9]

In [157]:
arr = np.array([[1, 2, 30], [4, 55, 6], [71, 8, 9]])

In [158]:
arr

array([[ 1,  2, 30],
       [ 4, 55,  6],
       [71,  8,  9]])

In [159]:
arr_float = np.array([[1, 2, 30], [4, 55, 6], [71, 8, 9]], dtype = 'float32')

In [168]:
arr_float

array([[ 1.,  2., 30.],
       [ 4., 55.,  6.],
       [71.,  8.,  9.]], dtype=float32)

In [170]:
arr_int = np.array([[1, 2, 30], [4, 55, 6], [71, 8, 9]], dtype = 'int32')

In [171]:
arr_int

array([[ 1,  2, 30],
       [ 4, 55,  6],
       [71,  8,  9]], dtype=int32)

In [172]:
arr_int[arr_int % 2 == 0]

array([ 2, 30,  4,  6,  8], dtype=int32)

In [173]:
arr_int.reshape((3, 3))

array([[ 1,  2, 30],
       [ 4, 55,  6],
       [71,  8,  9]], dtype=int32)

In [174]:
flat = arr_int.flatten()

In [175]:
flat

array([ 1,  2, 30,  4, 55,  6, 71,  8,  9], dtype=int32)

In [176]:
arr[arr_int>50]

array([55, 71])

In [177]:
arr = np.array([[1, 4.5, 73], [2.3, 333, 41], [19, 44, 12.54]])

In [178]:
arr

array([[  1.  ,   4.5 ,  73.  ],
       [  2.3 , 333.  ,  41.  ],
       [ 19.  ,  44.  ,  12.54]])

In [179]:
arr_int = np.array([[1, 4.5, 73], [2.3, 333, 41], [19, 44, 12.54]], dtype = 'int32')

In [180]:
arr_int

array([[  1,   4,  73],
       [  2, 333,  41],
       [ 19,  44,  12]], dtype=int32)

In [181]:
arr_int[arr_int % 2 == 0]

array([ 4,  2, 44, 12], dtype=int32)

In [182]:
arr_int.reshape((3, 3))

array([[  1,   4,  73],
       [  2, 333,  41],
       [ 19,  44,  12]], dtype=int32)

In [184]:
flat = arr_int.flatten()

In [190]:
flat

array([  1,   4,  73,   2, 333,  41,  19,  44,  12], dtype=int32)

In [194]:
arr[arr_int>50]

array([ 73., 333.])