In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0]

array([1, 2, 3])

### 1. Understanding Axes in NumPy

In [10]:
np.sum(arr, axis=0) # Sum of rows (down each column) 

array([12, 15, 18])

In [11]:
np.sum(arr, axis=1) # Sum of Columns (across each row)

array([ 6, 15, 24])

### 2. Indexing in Multidimensional Arrays

In [15]:
arr[0][1]  # Row index 0, Column index 1 --> output : 2

np.int64(2)

In [17]:
arr[0, 1]  # Row index 0, Column index 1 --> output : 2

np.int64(2)

In [18]:
arr[0:2, 1:3] # Extracts first 2 rows and last 2 columns

array([[2, 3],
       [5, 6]])

### 3. Indexing in 3D Arrays

In [19]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

In [30]:
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
print(arr3D.shape)

(2, 2, 3)


In [25]:
print(arr3D[0, 1, 2]) # First sheet, second row, third column

6


### 4. Practical Example: Selecting Data Along Axes

In [26]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [27]:
# Get all rows of the first column
first_col = arr3D[:, 0]
print(first_col)

[[1 2 3]
 [7 8 9]]


In [28]:
# Get the first row from each "sheet" in a 3D array.
first_row = arr3D[:, 0, :]
print(first_row)

[[1 2 3]
 [7 8 9]]


In [29]:
# Get the first column from each "sheet" in a 3D array.
first_col = arr3D[:, :, 1]
print(first_col)

[[ 2  5]
 [ 8 11]]


### 5. Changing Data Along an Axis

In [35]:
arr3D[:, 0, :] = 0

In [36]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])