### Broadcasting in NumPy

In [1]:
import numpy as np

Now, we'll explore how to make your code faster with vectorization and broadcasting in NumPy. These techniques are key to boosting performance in numerical operations by avoiding slow loops and memory inefficiency.

### 1. Why Loops Are Slow
In Python, loops are typically slow because:

- Python’s interpreter: Every iteration of the loop requires Python to interpret the loop logic, which is inherently slower than lower-level, compiled code.
- High overhead: Each loop iteration in Python involves additional overhead for function calls, memory access, and index management.

### 2. Vectorization: Fixing the Loop Problem

Vectorization allows you to perform operations on entire arrays at once, instead of iterating over elements one by one. This is made possible by NumPy’s optimized C-based backend that executes operations in compiled code, which is much faster than Python loops.

Vectorized operations are also more readable and compact, making your code easier to maintain.

Example: Vectorized Operation

In [2]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2   # Vectorized operation
print(result) 

[ 1  4  9 16 25]


### 3. Broadcasting: Scaling Arrays Without Extra Memory

Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes without creating copies. It “stretches” smaller arrays across larger arrays in a memory-efficient way, avoiding the overhead of creating multiple copies of data.

In [4]:
result = arr + 10
result

array([11, 12, 13, 14, 15])

### 4. Broadcasting with Arrays of Different Shapes

Broadcasting becomes more powerful when you apply operations on arrays of different shapes. NumPy automatically adjusts the shapes of arrays to make them compatible for element-wise operations, without actually copying the data.

In [7]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([7, 8, 9])
result = arr1 + arr2   # Broadcasting arr2 across arr1
print(result)

[[ 8 10 12]
 [11 13 15]]


### Simulating a dataset (5 samples, 3 features)

In [10]:
data = np.array([[10, 20, 30], [15, 25, 35], [20, 30, 40], [25, 35, 45], [30, 40, 50]])

In [12]:
# Calculating mean and standard deviation for each feature (column)

mean = data.mean(axis=0)
std = data.std(axis=0)

In [13]:
# Normalizing the data using broadcasting

normalized_data = (data - mean)/ std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


### Summary:
- Loops are slow because Python's interpreter adds overhead, making iteration less efficient.
- Vectorization allows you to apply operations to entire arrays at once, greatly improving performance by utilizing NumPy’s optimized C backend.
- Broadcasting enables operations between arrays of different shapes by automatically stretching the smaller array to match the shape of the -   larger array, without creating additional copies.
- Real-world use: Broadcasting can be used in data science tasks, such as normalizing datasets, without sacrificing memory or performance.