In [28]:
import numpy as np

In [29]:
arr = np.array([2, 3, 62, 16, 96])

In [30]:
print(np.mean(arr)) # Compute the mean (average) of an array.

35.8


In [31]:
print(np.min(arr)) # Compute the minimum value of an array.

2


In [32]:
print(np.max(arr)) # Compute the maximum value of an array.

96


In [33]:
print(np.std(arr)) # Compute the standard deviation of an array.

37.20430082665175


In [34]:
print(np.var(arr)) # Compute the variance of an array.

1384.16


In [35]:
print(np.sum(arr)) #  Compute the sum of all elements in an array.

179


In [36]:
print(np.prod(arr)) # Compute the product of all elements in an array.

571392


In [37]:
print(np.median(arr)) #  Compute the median of an array.

16.0


In [38]:
print(np.percentile(arr, 50)) # for the 50th percentile(median)

16.0


In [39]:
print(np.argmin(arr)) # Return the index of the minimum value in an array.

0


In [40]:
print(np.argmax(arr)) # Return the index of the maximum value in an array.

4


In [41]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [42]:
print(np.corrcoef(arr1, arr2)) # Compute the correlation coefficient matrix of two arrays.

[[1. 1.]
 [1. 1.]]


In [43]:
arr = np.array([2, 3, 62, 16, 96, 62, 1, 2])

In [44]:
print(np.unique(arr)) # Find the unique elements of an array.

[ 1  2  3 16 62 96]


In [46]:
print(np.cumsum(arr)) # Compute the cumulative sum of an array.

[  2   5  67  83 179 241 242 244]


In [48]:
print(np.diff(arr)) # Compute the n-th differences of an array.

[  1  59 -46  80 -34 -61   1]
