### Creating Numpy Arrays

In [48]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.full((4, 6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.arange(1, 100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [53]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [54]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [55]:
myarr.shape

(4, 3)

In [56]:
myarr.size

12

In [57]:
myarr.ndim

2

In [58]:
myarr.dtype

dtype('int64')

In [60]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]], dtype='float64')

In [61]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [62]:
myarr.shape

(4, 3)

In [63]:
reshaped = myarr.reshape((3, 4))

In [64]:
reshaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., 13.]])

In [65]:
#Original Array
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [67]:
myarr.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.])

### Indexing & Slicing

In [68]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [69]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [70]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [74]:
flat = myarr.flatten()

In [75]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [76]:
flat[0]

np.int64(1)

In [77]:
flat[1]

np.int64(2)

In [78]:
flat[3:6]

array([4, 5, 6])

In [79]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [80]:
flat[:6]

array([1, 2, 3, 4, 5, 6])

In [84]:
print(flat[::2])

[ 1  3  5  7  9 12]


In [85]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [88]:
b = flat[3:7].copy()

In [89]:
b

array([4, 5, 6, 7])

In [90]:
b[0] = 43434343

In [91]:
b

array([43434343,        5,        6,        7])

In [92]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [94]:
### Fancy Indexing(Select Multiple Elements)
arr = np.array([12, 34, 564, 684, 325, 5, 21, 2, 53, 3])
arr[[1, 4, 7]]

array([ 34, 325,   2])

In [95]:
### Boolean Masking(Filter Data) 
arr = np.array([12, 34, 564, 684, 325, 5, 21, 2, 53, 3])
arr[arr>25]

array([ 34, 564, 684, 325,  53])

In [96]:
### Example
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [97]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
arr1.shape

(3, 3)

In [103]:
arr_float = np.array([1.1, 2.2, 3.3])

In [107]:
arr_int = arr_float.astype(int)

In [108]:
print(arr_int)

[1 2 3]


In [109]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [111]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
np.sum(arr1, axis=1)

array([ 6, 15, 24])

In [114]:
np.sum(arr1, axis=0)

array([12, 15, 18])

In [115]:
arr1[0][1]

np.int64(2)

In [117]:
arr1[0, 1]

np.int64(2)

In [118]:
arr1[0:2, 1:3]

array([[2, 3],
       [5, 6]])

### Data Types in NumPy

In [1]:
import numpy as np

In [3]:
arr = np.array([23, 4, 34, 45])

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.astype("float64")

array([23.,  4., 34., 45.])

In [8]:
arr_int64 = np.array([23, 46, 49, 29], dtype=np.int64)

In [10]:
arr_int32 = np.array([23, 46, 49, 29], dtype=np.int32)

In [11]:
print(arr_int64.nbytes)
print(arr_int32.nbytes)

32
16


In [12]:
arr_complex = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)

In [15]:
print(arr_complex)

[1.+2.j 3.+4.j 5.+6.j]


### Vectorization & Broadcasting

In [19]:
#Vectorization
arr = np.array([23, 4, 34, 45])

In [20]:
result = arr ** 2

In [21]:
print(result)

[ 529   16 1156 2025]


In [22]:
#Broadcasting
result = arr + 10

In [23]:
print(result)

[33 14 44 55]


In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

In [26]:
result = arr1 + arr2

In [27]:
print(result)

[[2 4 6]
 [5 7 9]]


In [28]:
print(arr)

[23  4 34 45]


In [29]:
np.min(arr)

np.int64(4)

In [30]:
np.max(arr)

np.int64(45)

In [31]:
np.mean(arr)

np.float64(26.5)

In [33]:
np.std(arr)

np.float64(15.14100392972672)

In [34]:
np.argmin(arr)

np.int64(1)

In [35]:
np.argmax(arr)

np.int64(3)

In [36]:
np.corrcoef(arr)

np.float64(1.0)

In [37]:
np.unique(arr)

array([ 4, 23, 34, 45])

In [38]:
 np.cumsum(arr)

array([ 23,  27,  61, 106])

In [39]:
np.sum(arr)

np.int64(106)

In [40]:
np.prod(arr)

np.int64(140760)

In [41]:
np.percentile(arr, 50)

np.float64(28.5)

In [42]:
np.percentile(arr, 75)

np.float64(36.75)

In [43]:
np.percentile(arr, 25)

np.float64(18.25)

In [44]:
np.median(arr)

np.float64(28.5)

In [45]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [46]:
np.log(arr)

array([3.13549422, 1.38629436, 3.52636052, 3.80666249])

In [47]:
np.exp(arr)

array([9.74480345e+09, 5.45981500e+01, 5.83461743e+14, 3.49342711e+19])